import type { EvaluationRule } from "../types/index.js";

export const builtInRules: EvaluationRule[] = [
  {
    id: "block-rm-root",
    pattern: /^rm\s+-[^\s]*[rf][^\s]*\s+\/(?:\s|$)/,
    decision: "BLOCKED",
    reason: "recursive deletion of the filesystem root is destructive and never allowed",
    risk: "critical",
  },
  {
    id: "block-rm-wildcard-global",
    pattern: /^rm\s+-[^\s]*[rf][^\s]*\s+(?:\*|\.\/\*|~\/\*|\/[^ ]*\/\*)(?:\s|$)/,
    decision: "BLOCKED",
    reason: "broad wildcard deletes are destructive and too easy to misuse",
    risk: "critical",
  },
  {
    id: "block-curl-pipe-bash",
    pattern: /^curl\b.*\|\s*(?:bash|sh)(?:\s|$)/,
    decision: "BLOCKED",
    reason: "piping remote scripts directly into a shell bypasses inspection",
    risk: "critical",
  },
  {
    id: "block-wget-pipe-bash",
    pattern: /^wget\b.*\|\s*(?:bash|sh)(?:\s|$)/,
    decision: "BLOCKED",
    reason: "piping remote scripts directly into a shell bypasses inspection",
    risk: "critical",
  },
  {
    id: "block-mkfs",
    pattern: /^mkfs(?:\.[a-z0-9]+)?\b/,
    decision: "BLOCKED",
    reason: "filesystem formatting commands are destructive",
    risk: "critical",
  },
  {
    id: "block-dd-to-device",
    pattern: /^dd\b.*\bof=\/dev\/[a-z0-9/_-]+/,
    decision: "BLOCKED",
    reason: "writing raw data directly to block devices is destructive",
    risk: "critical",
  },
  {
    id: "block-sensitive-chmod",
    pattern: /^(?:sudo\s+)?chmod\b.*\s+(?:\/etc|\/bin|\/sbin|\/usr\/bin|\/usr\/sbin|\/var\/run|\/System)(?:\/|$)/,
    decision: "BLOCKED",
    reason: "changing permissions on sensitive system paths is blocked",
    risk: "critical",
  },
  {
    id: "block-sensitive-chown",
    pattern: /^(?:sudo\s+)?chown\b.*\s+(?:\/etc|\/bin|\/sbin|\/usr\/bin|\/usr\/sbin|\/var\/run|\/System)(?:\/|$)/,
    decision: "BLOCKED",
    reason: "changing ownership on sensitive system paths is blocked",
    risk: "critical",
  },
  {
    id: "require-deploy-release",
    pattern: /^(?:(?:npm|pnpm|yarn)\s+(?:run\s+)?(?:deploy|release)\b|(?:deploy|release)\b)/,
    decision: "REQUIRES_APPROVAL",
    reason: "deployment and release commands can change running systems",
    risk: "high",
  },
  {
    id: "require-npm-global-install",
    pattern: /^npm\s+install\s+-g\b/,
    decision: "REQUIRES_APPROVAL",
    reason: "global package installs change the local execution environment",
    risk: "high",
  },
  {
    id: "require-pip-upgrade",
    pattern: /^pip(?:3)?\s+install\b.*\s+--upgrade\b/,
    decision: "REQUIRES_APPROVAL",
    reason: "package upgrades can change runtime behavior and dependencies",
    risk: "high",
  },
  {
    id: "require-systemctl-restart",
    pattern: /^(?:sudo\s+)?systemctl\s+restart\b/,
    decision: "REQUIRES_APPROVAL",
    reason: "service restarts can interrupt running workloads",
    risk: "high",
  },
  {
    id: "require-kubectl-apply",
    pattern: /^kubectl\s+apply\b/,
    decision: "REQUIRES_APPROVAL",
    reason: "kubectl apply changes live cluster resources",
    risk: "high",
  },
  {
    id: "require-kubectl-delete",
    pattern: /^kubectl\s+delete\b/,
    decision: "REQUIRES_APPROVAL",
    reason: "kubectl delete removes live cluster resources",
    risk: "high",
  },
  {
    id: "require-helm-change",
    pattern: /^helm\s+(?:install|upgrade|uninstall|rollback)\b/,
    decision: "REQUIRES_APPROVAL",
    reason: "helm changes affect deployed services and cluster state",
    risk: "high",
  },
  {
    id: "require-terraform-apply",
    pattern: /^terraform\s+apply\b/,
    decision: "REQUIRES_APPROVAL",
    reason: "terraform apply changes infrastructure state",
    risk: "critical",
  },
  {
    id: "require-git-push-force",
    pattern: /^git\s+push\b.*\s--force(?:-with-lease)?(?:\s|$)|^git\s+push\b.*\s-f(?:\s|$)/,
    decision: "REQUIRES_APPROVAL",
    reason: "force pushes rewrite remote history",
    risk: "high",
  },
  {
    id: "require-ssh-command",
    pattern: /^ssh\b/,
    decision: "REQUIRES_APPROVAL",
    reason: "remote shell access should be reviewed before execution",
    risk: "high",
  },
  {
    id: "require-db-migration",
    pattern: /^(?:npm\s+run\s+db:migrate|pnpm\s+db:migrate|yarn\s+db:migrate|prisma\s+migrate\b|sequelize\s+db:migrate\b|alembic\s+upgrade\b|rails\s+db:migrate\b|dbmate\s+up\b)/,
    decision: "REQUIRES_APPROVAL",
    reason: "database migrations can change persistent state",
    risk: "high",
  },
  {
    id: "approve-ls",
    pattern: /^ls(?:\s+[^\n|><;]+)?$/,
    decision: "APPROVED",
    reason: "listing files is read-only",
    risk: "low",
  },
  {
    id: "approve-pwd",
    pattern: /^pwd$/,
    decision: "APPROVED",
    reason: "printing the working directory is read-only",
    risk: "low",
  },
  {
    id: "approve-echo",
    pattern: /^echo(?:\s+[^\n|><;]+)?$/,
    decision: "APPROVED",
    reason: "echo is read-only in this context",
    risk: "low",
  },
  {
    id: "approve-cat-normal-file",
    pattern: /^cat\s+(?!\/etc\/|\/var\/|\/proc\/|\/dev\/|~\/\.ssh|\.ssh\/)[^|><]+$/,
    decision: "APPROVED",
    reason: "reading a normal file is low risk",
    risk: "low",
  },
  {
    id: "approve-basic-diagnostics",
    pattern: /^(?:whoami|id|uname(?:\s+-a)?|ps(?:\s+[^\n|><;]+)?|df(?:\s+[^\n|><;]+)?|du(?:\s+[^\n|><;]+)?|which\s+[^\n|><;]+)$/,
    decision: "APPROVED",
    reason: "basic diagnostics are read-only",
    risk: "low",
  },
  {
    id: "approve-head-tail",
    pattern: /^(?:head|tail)\b(?!.*(?:\||>|>>|<|;)).+$/,
    decision: "APPROVED",
    reason: "reading part of a file is low risk",
    risk: "low",
  },
  {
    id: "approve-grep-readonly",
    pattern: /^grep\b(?!.*(?:\||>|>>|<|;)).+$/,
    decision: "APPROVED",
    reason: "searching file contents is read-only",
    risk: "low",
  },
  {
    id: "approve-find-readonly",
    pattern: /^find\b(?!.*(?:-delete|-exec|-ok|\||>|>>|<|;)).+$/,
    decision: "APPROVED",
    reason: "read-only file discovery is low risk",
    risk: "low",
  },
];
